# Generated by Django 2.1 on 2020-09-14 00:55

from django.db import migrations, models
import django.db.models.deletion
import tests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('name', models.CharField(max_length=80)),
                ('testScript', models.FileField(upload_to=tests.models.setPath)),
                ('framework', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.Framework')),
            ],
        ),
    ]
