# Generated by Django 2.1 on 2020-10-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20201018_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilerandomtest',
            name='ActivityName',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobilerandomtest',
            name='packageName',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reports',
            name='testResults',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
