# Generated by Django 2.1 on 2020-11-08 13:52

from django.db import migrations, models
import django.db.models.deletion
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20201025_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('image', models.ImageField(upload_to=tests.models.set_vrt_report_path)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Reports')),
            ],
        ),
    ]
