version: '2'
services:
  #backend
  backend:
    image: "backend-${ENVIRONMENT}-${CURRENT_BRANCH}-${COMMIT_HASH}"
    container_name: "backend-${ENVIRONMENT}"
    environment:
      - "DJANGO_SETTINGS_MODULE=backend.settings"
      - "RABBIT_IP=${RABBIT_IP}"
      - "RABBIT_PORT=${RABBIT_PORT}"
    ports:
      - "${BACKEND_IP}:${BACKEND_HTTP_PORT}:80"
    env_file: .env
  # django celery ---------------------------------------------------------------------
  celery:
    image: "backend-${ENVIRONMENT}-${CURRENT_BRANCH}-${COMMIT_HASH}"
    container_name: "backend-${ENVIRONMENT}-celery"
    environment:
      - "DJANGO_SETTINGS_MODULE=backend.settings"
      - "RABBIT_IP=${RABBIT_IP}"
      - "RABBIT_PORT=${RABBIT_PORT}"
    ports:
      - "${CELERY_IP}:${CELERY_HTTP_PORT}:80"
    command: /srv/www/bin/celery.sh
  # rabbit ---------------------------------------------------------------------
  rabbit:
    image: rabbitmq:3
    container_name: "rabbit-${ENVIRONMENT}"
    ports:
      - "${RABBIT_IP}:${RABBIT_PORT}:5672"
    hostname: "rabbit-${ENVIRONMENT}"

    # flower ---------------------------------------------------------------------
  flower:
    image: "backend-${ENVIRONMENT}-${CURRENT_BRANCH}-${COMMIT_HASH}"
    container_name: "backend-${ENVIRONMENT}-flower"
    environment:
      - "DJANGO_SETTINGS_MODULE=backend.settings"
      - "RABBIT_IP=${RABBIT_IP}"
      - "RABBIT_PORT=${RABBIT_PORT}"
    ports:
      - "${FLOWER_IP}:${FLOWER_HTTP_PORT}:80"
    command: /srv/www/bin/flower.sh
