version: '2'
services:
  #backend
  backend:
    image: "backend-${ENVIRONMENT}-${CURRENT_BRANCH}-${COMMIT_HASH}"
    container_name: "backend-${ENVIRONMENT}"
    environment:
      - "DJANGO_SETTINGS_MODULE=backend.settings"
      - "RABBIT_IP=${RABBIT_IP}"
      - "RABBIT_PORT=${RABBIT_PORT}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_IP=${POSTGRES_IP}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}"
      - "SENDGRID_API_KEY=${SENDGRID_API_KEY}"
    ports:
      - "${BACKEND_IP}:${BACKEND_HTTP_PORT}:80"
    env_file: .env
    depends_on:
      - database
    volumes:
      - medias:/srv/www/backend/backend/medias
  # django celery ---------------------------------------------------------------------
  celery:
    image: "backend-${ENVIRONMENT}-${CURRENT_BRANCH}-${COMMIT_HASH}"
    container_name: "backend-${ENVIRONMENT}-celery"
    environment:
      - "DJANGO_SETTINGS_MODULE=backend.settings"
      - "RABBIT_IP=${RABBIT_IP}"
      - "RABBIT_PORT=${RABBIT_PORT}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_IP=${POSTGRES_IP}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}"
      - "SENDGRID_API_KEY=${SENDGRID_API_KEY}"

    ports:
      - "${CELERY_IP}:${CELERY_HTTP_PORT}:80"
    command: /srv/www/bin/celery.sh
    volumes:
      - medias:/srv/www/backend/backend/medias
    depends_on:
      - database
      - rabbit
  # rabbit ---------------------------------------------------------------------
  rabbit:
    image: rabbitmq:3
    container_name: "rabbit-${ENVIRONMENT}"
    ports:
      - "${RABBIT_IP}:${RABBIT_PORT}:5672"
    hostname: "rabbit-${ENVIRONMENT}"
    depends_on:
      - database

  # postgres db ---------------------------------------------------------------------
  database:
    image: postgres
    container_name: "postgres-${ENVIRONMENT}"
    hostname: "postgres-${ENVIRONMENT}"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - "${POSTGRES_IP}:${POSTGRES_PORT}:5432"

    # flower ---------------------------------------------------------------------
  flower:
    image: "backend-${ENVIRONMENT}-${CURRENT_BRANCH}-${COMMIT_HASH}"
    container_name: "backend-${ENVIRONMENT}-flower"
    environment:
      - "DJANGO_SETTINGS_MODULE=backend.settings"
      - "RABBIT_IP=${RABBIT_IP}"
      - "RABBIT_PORT=${RABBIT_PORT}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_IP=${POSTGRES_IP}"
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}"
      - "SENDGRID_API_KEY=${SENDGRID_API_KEY}"

    ports:
      - "${FLOWER_IP}:${FLOWER_HTTP_PORT}:80"
    command: /srv/www/bin/flower.sh
    depends_on:
      - rabbit
    volumes:
      - medias:/srv/www/backend/backend/medias
volumes:
  medias: {}