# Generated by Django 2.1 on 2020-09-26 03:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('testResults', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('name', models.CharField(max_length=80)),
                ('appName', models.CharField(max_length=100)),
                ('appUrl', models.CharField(max_length=255)),
                ('appVersion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='BDDTest',
            fields=[
                ('testrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.TestRequest')),
                ('features', models.FileField(upload_to=tests.models.set_feature_bdd_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['feature'])])),
                ('stepsScript', models.FileField(upload_to=tests.models.set_js_bdd_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['js'])])),
            ],
            bases=('tests.testrequest',),
        ),
        migrations.CreateModel(
            name='End2End',
            fields=[
                ('testrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.TestRequest')),
                ('testScript', models.FileField(upload_to=tests.models.set_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['js'])])),
            ],
            bases=('tests.testrequest',),
        ),
        migrations.CreateModel(
            name='RandomTest',
            fields=[
                ('testrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.TestRequest')),
                ('eventsNumber', models.IntegerField()),
            ],
            bases=('tests.testrequest',),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='browser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.Browser', verbose_name='testing_browser'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.Framework'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.TestStrategy'),
        ),
        migrations.AddField(
            model_name='reports',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.TestRequest'),
        ),
    ]
